version: '3.3'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL={REACT_APP_BACKEND_URL}
      - GOOGLE_KEY={GOOGLE_KEY}
